import type { KolomDef } from "@/lib/indikator";

const OVERRIDES: Record<string, string> = {
  abs_id: "ID Absolut",
  subjek: "Jenis Subjek Data",
  datamasuk: "Tanggal Pendataan",
  enumerator: "Nama Petugas Pendata",
  kode_bangunan: "Kode Bangunan",
  kode_deskel: "Kode Desa/Kelurahan",
  deskel: "Desa/Kelurahan",
  dusun: "Dusun/Kampung/Dukuh",
  rw: "Rukun Warga (RW)",
  rt: "Rukun Tetangga (RT)",
  lat: "Koordinat Lintang",
  lng: "Koordinat Bujur",
  responden: "Kesediaan sebagai Responden",
  nkk: "Nomor Kartu Keluarga (No. KK)",
  nama: "Nama Lengkap",
  nik: "Nomor Induk Kependudukan (NIK)",
  alamat: "Alamat Rumah",
  status_dalam_keluarga: "Status dalam Keluarga",
  status_kawin: "Status Perkawinan Kepala dan Anggota Keluarga",
  punya_ktp: "Kepemilikan KTP/KIA",
  punya_aktalahir: "Kepemilikan Akta Kelahiran",
  nama_kepala_rumah: "Nama Kepala Rumah Tangga",
  nama_tulang_punggung: "Nama Tulang Punggung Keluarga",
  no_hp: "Nomor HP/WhatsApp Responden",
  jml_keluarga: "Jumlah Kepala dan Anggota Keluarga",
  tgl_lahir: "Tanggal Lahir",
  jk: "Jenis Kelamin",
  thn_datang: "Tahun Datang ke Desa",
  dinamika: "Dinamika Kehidupan",
  suku: "Etnis/Suku Kepala Keluarga",
  bhs_keluarga: "Bahasa dalam Keluarga",
  bhs_daerah: "Bahasa Daerah yang Dipakai",
  tgl_kawin: "Tanggal Perkawinan",
  usia_dec: "Usia Desimal",
  lama_tinggal: "Lama Tinggal (Tahun)",
  punya_kk: "Kepemilikan Kartu Keluarga",
  menetap: "Tinggal Menetap",
  dead_jml: "Jumlah Anggota Keluarga yang Meninggal",
  akta_nikah: "Kepemilikan Akta Nikah",
  akta_cerai: "Kepemilikan Akta Perceraian",
  partisipasi_sekolah: "Partisipasi Sekolah Kepala dan Anggota Keluarga",
  ijazah: "Pendidikan/Ijazah Terakhir",
  rp_pendidikan: "Pengeluaran Pendidikan Kepala dan Anggota Keluarga yang Sedang Bersekolah (SPP dan Uang Saku/Bulan)",
  pendidikan_anggota: "Jumlah Kepala dan Anggota Keluarga yang Sedang Sekolah",
  keterampilan: "Keterampilan yang Dimiliki Kepala Keluarga",
  pelatihan: "Keikutsertaan dalam Pelatihan",
  pelatihan_ket: "Jenis Pelatihan yang Diikuti",
  refreshing: "Frekuensi Liburan Keluarga (1 Tahun Terakhir)",
  pekarangan: "Kepemilikan Pekarangan Rumah yang Dapat Ditanami",
  pekarangan_luas: "Luas Pekarangan (m²)",
  pekarangan_air: "Sumber Air Pekarangan",
  pekarangan_tinggi: "Tinggi Dominan Tanaman Pekarangan",
  pekarangan_jenis: "Jenis Tanaman Pekarangan",
  pekarangan_komoditas: "Tanaman di Pekarangan Dua Tahun Terakhir",
  sampah_buang: "Tempat Membuang Sampah",
  sampah_pilah: "Pemilahan Sampah Organik dan Anorganik",
  sampah_olah: "Pengolahan Sampah",
  rumah_pln: "Daya PLN",
  rp_listrik: "Biaya Listrik per Bulan (Rp)",
  wifi: "Akses terhadap Internet Wi-Fi",
  airbersih: "Sumber Air Bersih Utama",
  airminum: "Sumber Air Minum Utama",
  bahanbakar_masak: "Bahan Bakar Masak Utama",
  rumah_solar: "Kepemilikan Panel Surya",
  par_organisasi: "Keterlibatan Organisasi Kepala Keluarga",
  organisasi_nama: "Nama Organisasi yang Diikuti Kepala Keluarga",
  par_masyarakat: "Partisipasi Kegiatan Masyarakat yang Diikuti Kepala Keluarga",
  par_pemilu: "Partisipasi Pemilu/Pilkada/Pilkades Kepala Keluarga",
  par_kebijakan: "Partisipasi dalam Perencanaan Kebijakan Kepala Keluarga",
  bansos: "Keikutsertaan Program Bantuan",
  rp_zakat: "Jumlah Zakat yang Dikeluarkan Selama Setahun Terakhir (Rp)",
  wakaf: "Wakaf yang Pernah Diberikan oleh Keluarga (Barang/Infrastruktur)",
  rp_persepuluh: "Jumlah Persepuluh yang Dikeluarkan Selama Setahun Terakhir (Rp)",
  rp_dharma: "Jumlah Dharma Dana yang Dikeluarkan Selama Setahun Terakhir (Rp)",
  rp_paramita: "Jumlah Dana Paramita yang Dikeluarkan (Rp)",
  rp_sumbangan: "Jumlah Sumbangan Sosial, Infak, dan Sedekah Setahun Terakhir (Rp)",
  disabilitas: "Jenis Disabilitas Kepala Keluarga",
  korban_kejahatan: "Pernah Menjadi Korban Kejahatan di Desa",
  hukum_bantuan: "Apakah Kepala Keluarga Pernah Mendapatkan Bantuan Hukum",
  hukum_jenis: "Bentuk Bantuan Hukum Kepala Keluarga",
  nomor_objek_pajak: "Nomor Objek Pajak (NOP)",
  pbb_punya: "Kepemilikan Pajak Bumi dan Bangunan (PBB)",
  pbb_tahunbayar: "Tahun Terakhir Membayar PBB",
  kesediaan: "Kesediaan Menjadi Responden",
  medsos: "Penggunaan Media Sosial",
  media_informasi: "Media Informasi",
  aset_ekonomi: "Aset-Aset Ekonomi yang Dimiliki",
  pinjaman: "Sumber Pinjaman",
  kb: "Keikutsertaan Keluarga Berencana (KB)",
  elektronik_rumah: "Kepemilikan Elektronik Rumahan",
  sepeda_jml: "Jumlah Kepemilikan Sepeda",
  motor_jml: "Jumlah Kepemilikan Sepeda Motor",
  motor_merk: "Merek Sepeda Motor",
  motorlistrik_jml: "Jumlah Kepemilikan Motor Listrik",
  mobil_jml: "Jumlah Kepemilikan Mobil",
  mobil_merk: "Merek Mobil",
  mobillistrik_jml: "Jumlah Kepemilikan Mobil Listrik",
  kendaraan_jml: "Jumlah Kendaraan Bermotor dalam Rumah Tangga",
  perahu_jml: "Jumlah Kepemilikan Perahu",
  perahu_motor_jml: "Jumlah Kepemilikan Perahu Motor",
  kapal_jml: "Jumlah Kepemilikan Kapal",
  rp_kendaraan: "Biaya Operasional Kendaraan per Tahun (Rp)",
  hp_punya: "Kepemilikan HP Kepala dan Anggota Keluarga",
  hp_jumlah: "Jumlah HP yang Dimiliki Kepala dan Anggota Keluarga",
  hp_merk: "Merek HP yang Digunakan",
  hp_provider: "Merek Provider yang Digunakan",
  rp_komunikasi: "Biaya Komunikasi per Bulan (Rp)",
  rp_transportasi: "Biaya Transportasi Umum per Bulan (Rp)",
  rp_cicilan: "Pengeluaran untuk Cicilan",
  baju_frek: "Frekuensi Beli Baju per Tahun Keluarga",
  rp_sph: "Biaya Sandang, Papan, dan Hiburan (Rp)",
  makan_frek: "Frekuensi Makan per Hari",
  makan_menu: "Menu Makan per Hari",
  tempat_belanja: "Tempat Membeli Kebutuhan Bahan Pokok Utama",
  rp_pangan: "Biaya Belanja Bulanan Pangan (Rp)",
  rp_non_pangan: "Biaya Belanja Bulanan Nonpangan (Rp)",
  kon_beras: "Beras (Liter) per Bulan",
  kon_biskuit: "Biskuit (Gram) per Bulan",
  kon_jagung: "Jagung (kg) per Bulan",
  kon_kentang: "Kentang (kg) per Bulan",
  kon_mie: "Mi (Bungkus) per Bulan",
  kon_roti: "Roti Tawar (Bungkus) per Bulan",
  kon_singkong: "Singkong (kg) per Bulan",
  kon_sukun: "Sukun (kg) per Bulan",
  kon_ketan: "Tape Beras Ketan (Liter) per Bulan",
  kon_sapi: "Daging Sapi (kg) per Bulan",
  kon_ayam: "Daging Ayam (kg) per Bulan",
  kon_babi: "Daging Babi (kg) per Bulan",
  kon_ikan_segar: "Ikan Segar (kg) per Bulan",
  kon_ikan_asin: "Ikan Kering/Asin (kg) per Bulan",
  kon_telur: "Telur Ayam (kg) per Bulan",
  kon_kacang_hijau: "Kacang Hijau (kg) per Bulan",
  kon_kacang_merah: "Kacang Merah (kg) per Bulan",
  kon_kacang_kedelai: "Kacang Kedelai (kg) per Bulan",
  kon_kacang_mede: "Kacang Mede (kg) per Bulan",
  kon_tahu: "Tahu (Bungkus) per Bulan",
  kon_tempe: "Tempe (Bungkus) per Bulan",
  kon_bayam: "Bayam (Ikat) per Bulan",
  kon_kangkung: "Kangkung (Ikat) per Bulan",
  kon_sawi: "Sawi (Ikat) per Bulan",
  kon_terong: "Terong (kg) per Bulan",
  kon_oyong: "Oyong (kg) per Bulan",
  kon_daun_singkong: "Daun Singkong (Ikat) per Bulan",
  kon_daun_ubi: "Daun Ubi (Ikat) per Bulan",
  kon_kelor: "Daun Kelor (Ikat) per Bulan",
  kon_jeruk: "Jeruk (kg) per Bulan",
  kon_mangga: "Mangga (kg) per Bulan",
  kon_pepaya: "Pepaya (kg) per Bulan",
  kon_pisang: "Pisang (kg) per Bulan",
  kon_alpukat: "Alpukat (kg) per Bulan",
  kon_semangka: "Semangka (kg) per Bulan",
  kon_melon: "Melon (kg) per Bulan",
  kon_cabai: "Cabai (kg) per Bulan",
  kon_bamer: "Bawang Merah (kg) per Bulan",
  kon_baput: "Bawang Putih (kg) per Bulan",
  kon_migor: "Minyak Goreng (Liter) per Bulan",
  kon_gas: "Gas (kg) per Bulan",
  kon_garam: "Garam (Gram) per Bulan",
  kon_gula: "Gula (kg) per Bulan",
  kon_susu: "Susu (Gelas) per Bulan",
  kon_teh: "Teh (Gelas) per Bulan",
  kon_kopi: "Kopi (Gelas) per Bulan",
  kon_rokok: "Rokok (Bungkus) per Bulan",
  kerja_profesi: "Pekerjaan/Profesi Utama",
  kerja_status: "Status Pekerjaan",
  kerja_ket: "Keterangan Pekerjaan Utama",
  kerja_lokusaha: "Lokasi Pekerjaan/Usaha",
  kerja_sampingan: "Pekerjaan Sampingan",
  kerja_sampingan_ket: "Keterangan Pekerjaan Sampingan",
  kerja_skalausaha: "Skala Usaha",
  nel_kepemilikan: "Status Nelayan Berdasarkan Kepemilikan",
  nel_waktu: "Status Nelayan Berdasarkan Waktu",
  nel_ukurankapal: "Status Nelayan Berdasarkan Ukuran Kapal",
  nel_penangkapan: "Area Operasi Penangkapan",
  nel_alat_tangkap: "Alat Tangkap yang Digunakan",
  nel_ikan_tangkap: "Jenis Tangkapan Utama",
  nel_ikan_kecil_perlakuan: "Kebiasaan terhadap Anak Ikan/Benih Ikan yang Tertangkap",
  nel_buang_sampah: "Tempat Pembuangan Sampah Aktivitas Nelayan",
  nel_pelatihan: "Pernah Mengikuti Pelatihan tentang Perikanan",
  nel_pelatihan_jenis: "Jenis Pelatihan Perikanan yang Pernah Diikuti",
  nel_budidaya_jenis: "Jenis Budidaya yang Dijalankan",
  nel_biota_jenis: "Jenis Biota yang Dibudidayakan",
  nel_budidaya_sarana: "Sarana Budidaya yang Digunakan",
  nel_sumber_air: "Sumber Air yang Digunakan untuk Budidaya",
  nel_bibit: "Sumber Bibit/Benih",
  nel_produksi: "Jumlah Produksi dalam Satu Siklus Panen",
  nel_hasil_jual: "Ke Mana Hasil Panen Dijual",
  nel_pernah: "Pernah Mengikuti Pelatihan Budidaya",
  bpjs_kes: "JKN-KIS/BPJS Kesehatan",
  asuransi_kes: "Asuransi Kesehatan selain BPJS",
  bpjs_tk: "Kepesertaan BPJS Ketenagakerjaan",
  tki: "Anggota Keluarga Bekerja sebagai TKI",
  tki_tujuan: "Negara Tujuan TKI",
  penyakit_jenis: "Jenis Penyakit Berat Kepala Keluarga",
  lahan: "Lahan yang Dimiliki atau Dikelola Keluarga",
  lahan_guna: "Pemanfaatan Lahan",
  lahan_luasnon: "Luas Lahan Nonpertanian",
  lahan_status: "Status Lahan Pertanian",
  lahan_luas_dikelola: "Total Luas Lahan Milik yang Dikelola (hektar)",
  lahan_luas_tidakdikelola: "Total Luas Lahan Milik yang Tidak Dikelola (hektar)",
  lahanmilik_irigasi: "Sumber Air Irigasi Lahan Milik",
  lahanmilik_bukti: "Bukti Kepemilikan Lahan Milik",
  lahanmilik_komoditas: "Riwayat Komoditas Lahan Milik",
  lahanmilik_lokasi: "Lokasi Lahan Milik",
  lahangarap_luas: "Luas Lahan Garap (hektar)",
  lahangarap_irigasi: "Sumber Air Irigasi Lahan Garap",
  lahangarap_komoditas: "Riwayat Komoditas Lahan Garap",
  lahangarap_lokasi: "Lokasi Lahan Garap",
  lahansewa_luas: "Luas Lahan Sewa (hektar)",
  lahansewa_irigasi: "Sumber Air Irigasi Lahan Sewa",
  lahansewa_komoditas: "Riwayat Komoditas Lahan Sewa",
  lahansewa_lokasi: "Lokasi Lahan Sewa",
  anak_asi: "Pemberian ASI Eksklusif",
  anak_periksa: "Pemeriksaan Kesehatan Anak",
  anak_mpasi: "Makanan Pendamping ASI (MPASI)",
  anak_tb: "Tinggi Badan Anak (cm)",
  anak_bb: "Berat Badan Anak (kg)",
  miskin_bps: "Status Kemiskinan BPS",
  miskin_ekstrem: "Status Kemiskinan Ekstrem",
  rumah_lantai: "Jenis Lantai Terluas",
  rumah_dinding: "Jenis Dinding Terluas",
  rumah_atap: "Jenis Atap Terluas",
  rumah_jamban: "Kepemilikan Jamban",
  rumah_kamar: "Jumlah Kamar Tidur",
  rumah_milik: "Status Kepemilikan Rumah",
  rumah_tingkat: "Jumlah Tingkat Rumah",
  rumah_luas: "Luas Bangunan Rumah (m²)",
  ternak: "Kepemilikan Ternak",
  ternak_sapi: "Jumlah Sapi",
  ternak_kerbau: "Jumlah Kerbau",
  ternak_domba: "Jumlah Domba",
  ternak_kambing: "Jumlah Kambing",
  ternak_ayam: "Jumlah Ayam",
  ternak_itik: "Jumlah Itik",
  ternak_kuda: "Jumlah Kuda",
  ternak_babi: "Jumlah Babi",
  ternak_ikan: "Jumlah Ikan (kg)",
};

const WORDS: Record<string, string> = {
  rp: "Nilai (Rp)",
  jml: "Jumlah",
  tgl: "Tanggal",
  thn: "Tahun",
  bhs: "Bahasa",
  par: "Partisipasi",
  kon: "Konsumsi",
  nel: "Nelayan",
  ket: "Keterangan",
  frek: "Frekuensi",
  punya: "Kepemilikan",
  jk: "Jenis Kelamin",
  nik: "NIK",
  nkk: "No. KK",
  kk: "KK",
  ktp: "KTP",
  hp: "HP",
  bpjs: "BPJS",
  pbb: "PBB",
  asi: "ASI",
  mpasi: "MPASI",
  tki: "TKI",
  pln: "PLN",
  wifi: "Wi-Fi",
  bps: "BPS",
  stnk: "STNK",
  uufm: "UuFm",
  wb: "World Bank",
  luasnon: "Luas Nonproduktif",
  lahanmilik: "Lahan Milik",
  lahangarap: "Lahan Garapan",
  lahansewa: "Lahan Sewa",
  lapusaha: "Lapangan Usaha",
  kerjapasca: "Pekerjaan Pascabencana",
  kesfungsional: "Kesehatan Fungsional",
  bagianrusak: "Bagian Rusak",
  ketenum: "Ketenagakerjaan Umum",
  bamer: "Bawang Merah",
  baput: "Bawang Putih",
  migor: "Minyak Goreng",
  sph: "Sandang per Hari",
};

function titleCase(word: string) {
  return word.length ? word[0].toUpperCase() + word.slice(1) : word;
}

/** A single display-name source for every database-backed field in the UI. */
export function fieldLabel(name: string, def?: Pick<KolomDef, "label">) {
  if (OVERRIDES[name]) return OVERRIDES[name];
  const generated = name
    .split("_")
    .map((word) => WORDS[word] ?? titleCase(word))
    .join(" ");
  if (generated && generated !== titleCase(name)) return generated;
  return (def?.label ?? generated)
    .replace(/\bNik\b/g, "NIK")
    .replace(/\bNkk\b/g, "No. KK")
    .replace(/\bRw\b/g, "RW")
    .replace(/\bRt\b/g, "RT")
    .replace(/\bHp\b/g, "HP")
    .replace(/\bBpjs\b/g, "BPJS")
    .replace(/\bPbb\b/g, "PBB")
    .replace(/\bKtp\b/g, "KTP")
    .replace(/\bKk\b/g, "KK");
}

export function enumOptionLabel(field: string, value: string) {
  if (field === "jk") return value === "L" ? "Laki-laki" : value === "P" ? "Perempuan" : value;
  return value;
}
